spring:
  profiles:
    active: dev
  application:
    name: backend

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  # Token expiration times:
  # 15 minutes = 900,000 ms
  access-expiration: ${JWT_ACCESS_EXPIRATION:900000}
  # 7 days = 604,800,000 ms
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operationsSorter: method
